### ISSUE TITLE
Windows (VS 2022) compilation errors...

### ISSUE THREAD

**Issue by proc-sim** [unageek/kigumi#14]
I'm trying to compile your code in Windows (latest VS 2022, C++20 Standard, latest Win10.0 SDK), and can't get past a huge list of errors that pop up immediately. I'm having a hard time tracking down the cause...any ideas? Thanks.

![compileErrors](https://github.com/unageek/kigumi/assets/2181360/e8aa73f9-aced-40ef-b21e-2f0223e9dd04)

**Comment by unageek** [comment]
Have you followed the [build instructions](https://github.com/unageek/kigumi/blob/main/docs/build-windows.md)? Building with Visual Studio is not supported.

**Comment by unageek** [comment]
Closing. Feel free to open a new issue if you have any further questions.
